name: Build and Deploy NodeJS App on AWS

on:
  push:
    branches:
      - main

jobs:
  Test-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5    

      - name: Basic Info
        run: |
          echo "hello to cicd"
          uname -a

      - name: Check Docker
        run: |
          docker --version
          docker info

      - name: List Docker Images
        run: docker images

      - name: List Running Containers
        run: docker ps -a
