name: Build and Deploy NodeJS App on AWS
on:
  push:
    branches:
    - main
  
jobs:
  Build-App:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5    

      - name: Build the Docker Image
        run: 
          echo "hello to cicd"
          uname -a
